"""Render the README results block from the JSON artifacts.

The README's numbers are never typed by hand: this module regenerates
the block between the RESULTS markers from `metrics.json`,
`comparison.json`, `sensitivity.json`, `tuning.json` and
`explainability.json` (the last three optional). `--check` exits non-zero if
the README is out of date, which is what keeps README and artifacts in
step (CLAUDE.md "Definition of done").

Usage:
    python -m credit_default.report            # rewrite the README block
    python -m credit_default.report --check    # fail if it is stale
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

START = "<!-- RESULTS:START (generated by `python -m credit_default.report` - do not edit) -->"
END = "<!-- RESULTS:END -->"


def _load(artifacts: Path, name: str) -> dict | None:
    path = artifacts / name
    return json.loads(path.read_text()) if path.exists() else None


def render_tuning(tuning: dict) -> list[str]:
    scoring = tuning["scoring"]
    cur_mean = tuning[f"current_cv_mean_{scoring}"]
    cur_std = tuning[f"current_cv_std_{scoring}"]
    best = tuning["best"]
    stds = tuning["gain_in_current_cv_stds"]
    if stds is not None and stds >= 1.0:
        verdict = "The gain exceeds one CV standard deviation; adopting the searched values is worth considering."
    else:
        verdict = (
            "The gain is within CV noise (under one standard deviation), so the "
            "configured parameters were kept."
        )
    return [
        "",
        f"**Hyperparameter search** (random search, {tuning['n_iter']} candidates, "
        f"{tuning['cv_folds']}-fold CV on the training split, scored on {scoring}):",
        "",
        "| | CV score | Parameters |",
        "|---|---|---|",
        f"| Current configuration | {cur_mean:.4f} ± {cur_std:.4f} | "
        + ", ".join(f"{k}={v}" for k, v in tuning["current_params"].items() if k != "eval_metric")
        + " |",
        f"| Best of search | {best[f'cv_mean_{scoring}']:.4f} ± {best[f'cv_std_{scoring}']:.4f} | "
        + ", ".join(
            f"{k}={v:.3g}" if isinstance(v, float) else f"{k}={v}" for k, v in best["params"].items()
        )
        + " |",
        "",
        f"Gain: {tuning['gain_over_current']:+.4f} "
        + (f"({stds:+.2f} current-CV standard deviations). " if stds is not None else ". ")
        + verdict
        + " The best-of-search score is selected as a maximum over noisy estimates and is "
        "optimistically biased.",
    ]


FEATURE_GROUPS = [
    ("Repayment status", "PAY_0, PAY_2–PAY_6"),
    ("Payment amounts", "PAY_AMT1–6"),
    ("Bill amounts", "BILL_AMT1–6"),
    ("Credit limit", "LIMIT_BAL"),
    ("Demographics", "SEX, EDUCATION, MARRIAGE, AGE"),
]
STRONG_DIRECTION = 0.7  # |rank correlation| above which a direction is stated
MATERIAL_SHARE = 0.10   # demographic share at or above which it is called material, not small


def feature_group(feature: str) -> str:
    if feature.startswith("PAY_AMT"):
        return "Payment amounts"
    if feature.startswith("PAY_"):
        return "Repayment status"
    if feature.startswith("BILL_AMT"):
        return "Bill amounts"
    if feature == "LIMIT_BAL":
        return "Credit limit"
    if feature in {"SEX", "EDUCATION", "MARRIAGE", "AGE"}:
        return "Demographics"
    return "Other"


def group_shares(features: list[dict]) -> dict[str, float]:
    shares: dict[str, float] = {}
    for r in features:
        g = feature_group(r["feature"])
        shares[g] = shares.get(g, 0.0) + r["share_of_total"]
    return shares


def explainability_observations(expl: dict, top_n: int = 10) -> list[str]:
    """Plain-language observations derived only from the numbers in the
    artifact, so they cannot disagree with the table above them."""
    feats = expl["features"]
    top = feats[0]
    top3 = sum(r["share_of_total"] for r in feats[:3])
    shares = group_shares(feats)
    ranked_groups = sorted(shares.items(), key=lambda kv: kv[1], reverse=True)
    obs = [
        f"`{top['feature']}` is the single most influential feature "
        f"({top['share_of_total']:.1%} of total importance); the top three features together "
        f"account for {top3:.1%}.",
        f"By group, {ranked_groups[0][0].lower()} features carry the most importance "
        f"({ranked_groups[0][1]:.1%}), followed by {ranked_groups[1][0].lower()} "
        f"({ranked_groups[1][1]:.1%}).",
    ]
    lower = [r["feature"] for r in feats[:top_n]
             if r["direction_corr"] is not None and r["direction_corr"] <= -STRONG_DIRECTION]
    higher = [r["feature"] for r in feats[:top_n]
              if r["direction_corr"] is not None and r["direction_corr"] >= STRONG_DIRECTION]
    if lower:
        obs.append(
            "Higher values of " + ", ".join(f"`{f}`" for f in lower) +
            f" push the score towards lower default risk (rank correlation ≤ −{STRONG_DIRECTION})."
        )
    if higher:
        obs.append(
            "Higher values of " + ", ".join(f"`{f}`" for f in higher) +
            f" push the score towards higher default risk (rank correlation ≥ +{STRONG_DIRECTION})."
        )
    demo = shares.get("Demographics")
    if demo is not None:
        size = "small but not zero" if demo < MATERIAL_SHARE else "a material share"
        obs.append(
            f"The demographic features (`SEX`, `EDUCATION`, `MARRIAGE`, `AGE`) account for "
            f"{demo:.1%} of total importance. That is {size}, so the protected-"
            "characteristic caveat under Limitations applies."
        )
    return obs


def _figure(expl: dict, index: int) -> list[str]:
    figures = expl.get("figures", [])
    if index >= len(figures):
        return []
    return ["", f"![{figures[index]['alt']}]({figures[index]['path']})"]


def render_explainability(expl: dict, top_n: int = 10) -> list[str]:
    lines = [
        "",
        f"**Feature importance (SHAP)** — {expl['method']}, on a {expl['n_rows']:,}-row "
        f"sample of the training split; top {top_n} of {len(expl['features'])} features:",
    ]
    lines += _figure(expl, 0)  # importance bars, coloured by the groups tabulated below
    lines += [
        "",
        "| Feature | Mean \\|SHAP\\| | Share of total | Rank corr. (value vs SHAP) |",
        "|---|---|---|---|",
    ]
    for r in expl["features"][:top_n]:
        corr = f"{r['direction_corr']:+.2f}" if r["direction_corr"] is not None else "n/a (categorical)"
        lines.append(
            f"| {r['feature']} | {r['mean_abs_shap']:.3f} | {r['share_of_total']:.1%} | {corr} |"
        )
    shares = group_shares(expl["features"])
    lines += [
        "",
        "Importance by feature group:",
        "",
        "| Group | Features | Share of total importance |",
        "|---|---|---|",
    ]
    for name, members in FEATURE_GROUPS:
        if name in shares:
            lines.append(f"| {name} | {members} | {shares[name]:.1%} |")
    if "Other" in shares:
        lines.append(f"| Other | — | {shares['Other']:.1%} |")

    lines += _figure(expl, 1)  # per-client dot plot: direction of each feature's effect
    lines += ["", "Observations (derived from the tables above):", ""]
    lines += [f"- {o}" for o in explainability_observations(expl, top_n)]
    lines += [
        "",
        "Caveats: SHAP values describe what the model relies on, not causal effects, "
        "and were computed on training data, so they say nothing about how well these "
        "relationships generalise. The rank correlation is a one-number summary that can "
        "hide non-monotone relationships (e.g. `PAY_0` status codes are not ordered "
        "quantities); treat the notebook's dot plot as the better guide to direction.",
    ]
    return lines


def render_results(
    metrics: dict,
    comparison: dict | None,
    sensitivity: dict | None,
    tuning: dict | None = None,
    explainability: dict | None = None,
) -> str:
    cm = metrics["confusion_matrix"]
    ds = metrics["dataset"]
    lines = [
        f"**Main model: {metrics['model_type']}** — {ds['n_train']:,} train / "
        f"{ds['n_test']:,} test rows, default rate {ds['test_default_rate']:.1%} in test. "
        f"Precision floor: {metrics['min_precision_constraint']}.",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| CV average precision (train) | {metrics['cv_mean_average_precision']:.3f} "
        f"± {metrics['cv_std_average_precision']:.3f} |",
        f"| Test ROC AUC | {metrics['roc_auc']:.3f} |",
        f"| Test average precision | {metrics['average_precision']:.3f} |",
        f"| Chosen threshold (score cut-off) | {metrics['chosen_threshold']:.3f} |",
        f"| Out-of-fold precision / recall at threshold (train) | "
        f"{metrics['threshold_oof_precision']:.3f} / {metrics['threshold_oof_recall']:.3f} |",
        f"| **Test precision / recall at threshold** | "
        f"**{metrics['precision']:.3f} / {metrics['recall']:.3f}** |",
        f"| Test confusion matrix (TN / FP / FN / TP) | "
        f"{cm['true_negative']} / {cm['false_positive']} / "
        f"{cm['false_negative']} / {cm['true_positive']} |",
    ]

    if comparison:
        lines += [
            "",
            f"**Model comparison** (ranked by {comparison['ranked_by']}; test columns "
            "are reported, not used for selection):",
            "",
            "| Model | CV AP | Test P / R at 0.5 | Test P / R at floor |",
            "|---|---|---|---|",
        ]
        for m in comparison["models"]:
            d = m.get("at_default_threshold")
            at_half = f"{d['precision']:.3f} / {d['recall']:.3f}" if d else "n/a"
            at_floor = (
                f"{m['precision']:.3f} / {m['recall']:.3f}" if "precision" in m else "infeasible"
            )
            lines.append(
                f"| {m['name']} | {m['cv_mean_average_precision']:.3f} | {at_half} | {at_floor} |"
            )

    if sensitivity:
        lines += [
            "",
            "**Sensitivity to the precision floor** (main model, test set):",
            "",
            "| Floor | Test precision | Test recall | Share of clients flagged | "
            "False positives per true positive |",
            "|---|---|---|---|---|",
        ]
        for r in sensitivity["floors"]:
            if not r["feasible"]:
                lines.append(f"| {r['min_precision']} | infeasible | | | |")
                continue
            lines.append(
                f"| {r['min_precision']} | {r['test_precision']:.3f} | {r['test_recall']:.3f} "
                f"| {r['flagged_share_of_test']:.1%} | "
                f"{r['false_positives_per_true_positive']:.2f} |"
            )

    if tuning:
        lines += render_tuning(tuning)
    if explainability:
        lines += render_explainability(explainability)
    return "\n".join(lines)


def replace_block(readme: str, block: str) -> str:
    if START not in readme or END not in readme:
        raise ValueError("README is missing the RESULTS:START / RESULTS:END markers")
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{block}\n{END}{tail}"


def verify_figures(expl: dict | None, readme_dir: Path) -> None:
    """Every figure the artifact lists must exist next to the README and be
    byte-identical to what `explain` wrote, so an image cannot sit under
    numbers it was not generated from."""
    for fig in (expl or {}).get("figures", []):
        path = readme_dir / fig["path"]
        if not path.exists():
            raise FileNotFoundError(f"{path} not found; run `python -m credit_default.explain`")
        if hashlib.sha256(path.read_bytes()).hexdigest() != fig["sha256"]:
            raise ValueError(
                f"{path} does not match explainability.json (stale or edited); "
                "re-run `python -m credit_default.explain`"
            )


def build(readme_path: Path, artifacts: Path) -> str:
    metrics = _load(artifacts, "metrics.json")
    if metrics is None:
        raise FileNotFoundError(f"{artifacts / 'metrics.json'} not found; run training first")
    explainability = _load(artifacts, "explainability.json")
    verify_figures(explainability, readme_path.parent)
    block = render_results(
        metrics,
        _load(artifacts, "comparison.json"),
        _load(artifacts, "sensitivity.json"),
        _load(artifacts, "tuning.json"),
        explainability,
    )
    return replace_block(readme_path.read_text(encoding="utf-8"), block)


def main(readme: str, artifacts: str, check: bool) -> int:
    readme_path = Path(readme)
    new = build(readme_path, Path(artifacts))
    if check:
        if new != readme_path.read_text(encoding="utf-8"):
            print("README results block is stale; run: python -m credit_default.report")
            return 1
        print("README results block is up to date")
        return 0
    readme_path.write_text(new, encoding="utf-8", newline="\n")
    print(f"Updated {readme_path}")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--readme", default="README.md")
    parser.add_argument("--artifacts", default="artifacts")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sys.exit(main(args.readme, args.artifacts, args.check))
